#!/usr/bin/env bash
# script displays
# to infinity and beyond indefinitely
# I am invincible!!! when receiving a SIGTERM signal

trap 'echo "I am invincible!!!"' 15
while true; do
    echo "to infinity and beyond"
    sleep 2
done
