#!/bin/bash

# Bash script to connect to the server using a private key with ssh

# Server IP address
server_ip="8.8.8.8"

# SSH command using the private key (~/.ssh/school) and the user (ubuntu)
ssh -i ~/.ssh/school ubuntu@$server_ip
